# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               SYNCSRC
tagline:             'Exploring Trust Issues'
description:         'The content here does not reflect the opinions of any government, company, organization or person.'
baseurl:             http://www.syncsrc.org
paginate:            5

# About/contact
author:
  name:              Matt
  url:               http://www.syncsrc.org
  twitter:           syncsrc
  email:             contact@syncsrc.org

# Custom vars
version:             1.0.0
