# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               SYNCSRC
tagline:             'Computers are terrible'
description:         'The content here does not reflect the opinions of any government, company, organization or person.'
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Matt
  url:               https://twitter.com/syncsrc
  email:             jtag@syncsrc.org

# Custom vars
version:             1.0.0
